config/routes.rb
Rails.application.routes.draw do
  resources :bicycle_shops, only: [:index]
  devise_for :users, controllers: {
    'omniauth_callbacks': 'users/omniauth_callbacks'
  }
  
  resources :events, only: [:index, :show] do
    resources :comments, only: [:create,:destroy]
  end
  resources :categories, only: [:index, :show]
  resources :products, only: [:index, :show]
  resources :in_shopping_carts, only: [:create, :destroy, :update]

  root 'products#index'

  # Admin routes
  namespace :admin do
    resources :users
    resources :categories
    resources :events
    resources :my_payments
    resources :products

    root "products#index"
  end
  

  get '/cart', to: 'shopping_carts#show'
  get '/add/:product_id', as: :add_to_cart, to: 'in_shopping_carts#create'
  get '/checkout', to: 'payments#checkout'
  get '/ok', to: 'home#success'
  # get '/download/:id', to: 'links#download'
  # get '/download/:id/file/:attachment_id', to: 'links#download_attachment', as: :download_attachment
  # get '/invalid', to: 'welcome#unregistered'
  get '/orders', to: 'orders#index'
  get '/about', to: 'home#about'
  get '/terms', to: 'home#terms'

  post '/pay', to: 'payments#create'
  post 'payments/cards', to: 'payments#process_card'

  post '/events/:id/attend', to: 'events#attend', as: :attend

  post '/custom_sign_up', to: 'users/omniauth_callbacks#custom_sign_up'
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :event

  validates :content, presence: true
  validates :rating, numericality: { only_integer: true }, inclusion: 1..5
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_event
  before_action :set_comment, only: [:update, :destroy]

  # # GET /comments
  # # GET /comments.json
  # def index
  #   @comments = Comment.all
  # end

  # # GET /comments/1
  # # GET /comments/1.json
  # def show
  # end

  # # GET /comments/new
  # def new
  #   @comment = Comment.new
  # end

  # # GET /comments/1/edit
  # def edit
  # end

  # POST /comments
  # POST /comments.json
  def create
    @comment = current_user.comments.new(comment_params)
    @comment.event = @event

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment.event, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment.event }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # # PATCH/PUT /comments/1
  # # PATCH/PUT /comments/1.json
  # def update
  #   respond_to do |format|
  #     if @comment.update(comment_params)
  #       format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
  #       format.json { render :show, status: :ok, location: @comment }
  #     else
  #       format.html { render :edit }
  #       format.json { render json: @comment.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    if current_user == @comment.user
      @comment.destroy

      respond_to do |format|
        format.html { redirect_to @comment.event, notice: 'Comment was successfully destroyed.' }
        format.json { head :no_content }
      end
    else
      respond_to do |format|
        format.html { redirect_to @comment.event, notice: 'No tienes permisos para realizar esta acción' }
        format.json { head :no_content }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    def set_event
      @event = Event.find(params[:event_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:content, :rating)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.haml
.media.pb-4
  -# %a.float-left{:href => "#pablo"}
  .avatar
    %img.media-object{alt: "64x64", src: "http://cdn.akamai.steamstatic.com/steamcommunity/public/images/avatars/47/474eb3fe7b60652d73dd1435b8f0e3a9b53ecb2d_full.jpg"}/
  .media-body
    %h4.media-heading.mb-0
      = comment.user.name.full
      %small
        ·
        = comment.created_at.strftime('%A,  %B %e')
        -# = comment.created_at.strftime('%b, %e %Y, %l:%M %p')
    .d-block.text-warning
      - comment.rating.to_i.times do
        %i.material-icons star
      - blank_stars = 5 - comment.rating
      - blank_stars.times do
        %i.material-icons star_border
    %p= comment.content
    - if user_signed_in?
      - if current_user == comment.user
        .media-footer
          = link_to [comment.event,comment], method: :delete, class: 'btn btn-danger btn-link float-right', "data-original-title" => 'Eliminar comentario', rel: "tooltip", title: 'Eliminar comentario', data: {confirm:'¿Estás seguro? Esta acción no se puede deshacer'} do
            %i.material-icons delete
            Eliminar
          -# %a.btn.btn-danger.btn-link.float-right{:href => "#pablo"}
          -#   %i.material-icons favorite
          -#   243

app/views/comments/_form.html.haml
= form_for [@event, @comment] do |f|
  - if @comment.errors.any?
    #error_explanation
      %h2= "#{pluralize(@comment.errors.count, "error")} prohibited this comment from being saved:"
      %ul
        - @comment.errors.full_messages.each do |message|
          %li= message
  .form-group.bmd-form-group
    = f.label :rating
    .rate.d-flex.flex-row-reverse.justify-content-end
      = f.radio_button :rating, 5, id: "star5"
      %label{for: "star5", title: "5 estrellas"} 5 estrellas
      = f.radio_button :rating, 4, id: "star4"
      %label{for: "star4", title: "4 estrellas"} 4 estrellas
      = f.radio_button :rating, 3, id: "star3"
      %label{for: "star3", title: "3 estrellas"} 3 estrellas
      = f.radio_button :rating, 2, id: "star2"
      %label{for: "star2", title: "2 estrellas"} 2 estrellas
      = f.radio_button :rating, 1, id: "star1"
      %label{for: "star1", title: "1 estrellas"} 1 estrella
  .form-group.bmd-form-group
    = f.label :content, "Escribe aquí tu comentario", class: 'bmd-label-floating'
    = f.text_area :content, class: 'form-control', required: true, size: "2x5"
  .actions
    = f.submit 'Comentar 👉', class: 'btn btn-success btn-wd'

app/views/comments/edit.html.haml
%h1 Editing comment

= render 'form'

= link_to 'Show', @comment
\|
= link_to 'Back', comments_path

app/views/comments/index.html.haml
%h1 Listing comments

%table
  %thead
    %tr
      %th Content
      %th Rating
      %th User
      %th Event
      %th
      %th
      %th

  %tbody
    - @comments.each do |comment|
      %tr
        %td= comment.content
        %td= comment.rating
        %td= comment.user
        %td= comment.event
        %td= link_to 'Show', comment
        %td= link_to 'Edit', edit_comment_path(comment)
        %td= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Comment', new_comment_path

app/views/comments/new.html.haml
%h1 New comment

= render 'form'

= link_to 'Back', comments_path

app/views/comments/show.html.haml
%p#notice= notice

%p
  %b Content:
  = @comment.content
%p
  %b Rating:
  = @comment.rating
%p
  %b User:
  = @comment.user
%p
  %b Event:
  = @comment.event

= link_to 'Edit', edit_comment_path(@comment)
\|
= link_to 'Back', comments_path