config/routes.rb
Rails.application.routes.draw do
  resources :bicycle_shops, only: [:index]
  devise_for :users, controllers: {
    'omniauth_callbacks': 'users/omniauth_callbacks'
  }
  
  resources :events, only: [:index, :show] do
    resources :comments, only: [:create,:destroy]
  end
  resources :categories, only: [:index, :show]
  resources :products, only: [:index, :show]
  resources :in_shopping_carts, only: [:create, :destroy, :update]

  root 'products#index'

  # Admin routes
  namespace :admin do
    resources :users
    resources :categories
    resources :events
    resources :my_payments
    resources :products

    root "products#index"
  end
  

  get '/cart', to: 'shopping_carts#show'
  get '/add/:product_id', as: :add_to_cart, to: 'in_shopping_carts#create'
  get '/checkout', to: 'payments#checkout'
  get '/ok', to: 'home#success'
  # get '/download/:id', to: 'links#download'
  # get '/download/:id/file/:attachment_id', to: 'links#download_attachment', as: :download_attachment
  # get '/invalid', to: 'welcome#unregistered'
  get '/orders', to: 'orders#index'
  get '/about', to: 'home#about'
  get '/terms', to: 'home#terms'

  post '/pay', to: 'payments#create'
  post 'payments/cards', to: 'payments#process_card'

  post '/events/:id/attend', to: 'events#attend', as: :attend

  post '/custom_sign_up', to: 'users/omniauth_callbacks#custom_sign_up'
end

app/views/partials/_alerts.haml
- if alert || notice
  .alert#alert{class: "alert-info #{'alert-danger' if alert}"}
    %button.close{"aria-label" => "Close", "data-dismiss" => "alert", :type => "button"}
      %i.material-icons close
    = alert
    = notice

app/views/partials/_footer.haml
%footer.footer
  .container
    .row
      .col-12
        %ul.social-buttons
          %li
            %a.btn.btn-link.btn-just-icon.btn-facebook{href: "https://www.facebook.com/app.geobike.co", target: "_blank"}
              %i.fa.fa-facebook-square
          %li
            %a.btn.btn-link.btn-just-icon.btn-link{href: "https://instagram.com/geobike_co", target: "_blank"}
              %i.fa.fa-instagram
          %li
            %a.btn.btn-link.btn-just-icon.btn-twitter{href: "https://twitter.com/JavierRiiveros", target: "_blank"}
              %i.fa.fa-twitter 
    %nav.float-left
      %ul
        %li= link_to "Geobike", root_path
        %li= link_to "Acerca de", about_path
        %li= link_to "Términos y condiciones", terms_path
    .copyright.float-right
      ©
      GeoBike 2019. Todos los derechos reservados.

app/views/partials/_nav.haml
%nav#sectionsNav.navbar.navbar-color-on-scroll.navbar-transparent.fixed-top.navbar-expand-lg{"color-on-scroll" => "100", "data-turbolinks-permanent": true}
  .container
    .navbar-translate
      = link_to root_path, class: 'navbar-brand' do
        GeoBike
      %button.navbar-toggler{"aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.navbar-toggler-icon
        %span.navbar-toggler-icon
        %span.navbar-toggler-icon
    .collapse.navbar-collapse
      %ul.navbar-nav.ml-auto
        %li.nav-item
          = link_to products_path, class: 'nav-link' do
            %i.material-icons receipt
            Productos
        %li.nav-item
          = link_to events_path, class: 'nav-link' do
            %i.material-icons event
            Eventos
        - if user_signed_in?
          %li.dropdown.nav-item
            = link_to "#", id: "logoutDropdown", class: 'nav-link dropdown-toggle', role: "button", "data-toggle": "dropdown", "aria-haspopup": "true", "aria-expanded": false do
              %i.material-icons face
              = current_user.name.mentionable
            .dropdown-menu.dropdown-with-icons{"aria-labelledby": "logoutDropdown"}
              = link_to 'Cerrar sesión', destroy_user_session_path, method: :delete, class: 'dropdown-item'
        - else
          %li.nav-item
            = link_to new_user_session_path, class: 'nav-link', "data-placement": "bottom", "data-toggle": "tooltip", title: "Iniciar sesión" do
              %i.material-icons fingerprint
              -# Iniciar sesión
          %li.nav-item
            = link_to new_user_registration_path, class: 'nav-link', "data-placement": "bottom", "data-toggle": "tooltip", title: "Crear cuenta" do
              %i.material-icons person_add
              -# Crear cuenta
        %li.button-container.nav-item.iframe-extern
          = link_to cart_path, class: 'btn btn-rose btn-round btn-block' do
            %i.material-icons shopping_cart
            (
            %span#cart-size{"data-turbolinks-permanent": true}= @shopping_cart.products.count
            )
            Ver carrito

app/views/partials/_search.haml
= form_tag products_path, method: :get, class: 'w-100' do
  .input-group.mt-3
    = select_tag :category, options_from_collection_for_select(@categories, 'id', 'name', {selected: @category}), {include_blank: 'Busque por categoría', class: 'selectpicker custom-width',data: {style: 'select-with-transition'}}
    -# = text_field_tag :keyword, nil, placeholder: "Buscar", class: "form-control", value: @keyword, required: true
    %span.input-group-append
      = content_tag :button, type: :submit, class: "btn btn-info btn-round" do
        %i.glyphicon.glyphicon-search
        Buscar