config/routes.rb
Rails.application.routes.draw do
  resources :bicycle_shops, only: [:index]
  devise_for :users, controllers: {
    'omniauth_callbacks': 'users/omniauth_callbacks'
  }
  
  resources :events, only: [:index, :show] do
    resources :comments, only: [:create,:destroy]
  end
  resources :categories, only: [:index, :show]
  resources :products, only: [:index, :show]
  resources :in_shopping_carts, only: [:create, :destroy, :update]

  root 'products#index'

  # Admin routes
  namespace :admin do
    resources :users
    resources :categories
    resources :events
    resources :my_payments
    resources :products

    root "products#index"
  end
  

  get '/cart', to: 'shopping_carts#show'
  get '/add/:product_id', as: :add_to_cart, to: 'in_shopping_carts#create'
  get '/checkout', to: 'payments#checkout'
  get '/ok', to: 'home#success'
  # get '/download/:id', to: 'links#download'
  # get '/download/:id/file/:attachment_id', to: 'links#download_attachment', as: :download_attachment
  # get '/invalid', to: 'welcome#unregistered'
  get '/orders', to: 'orders#index'
  get '/about', to: 'home#about'
  get '/terms', to: 'home#terms'

  post '/pay', to: 'payments#create'
  post 'payments/cards', to: 'payments#process_card'

  post '/events/:id/attend', to: 'events#attend', as: :attend

  post '/custom_sign_up', to: 'users/omniauth_callbacks#custom_sign_up'
end

app/models/event.rb
# == Schema Information
#
# Table name: events
#
#  id         :bigint(8)        not null, primary key
#  name       :string
#  details    :text
#  starts_at  :datetime
#  ends_at    :datetime
#  location   :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Event < ApplicationRecord
  has_one_attached :image
  validates_presence_of :name, :details, :location

  has_many :attend
  has_many :users, through: :attend, foreign_key: 'event_id'
  has_many :comments

  scope :latest, -> { order('id DESC') }
  scope :upcoming, -> { where('starts_at > ?', Date.today) }
  scope :past, -> { where('starts_at < ?', Date.today) }
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, only: [:attend]
  before_action :set_event, only: [:show, :edit, :update, :destroy, :attend]

  # GET /events
  # GET /events.json
  def index
    if !params[:date].nil?
      @date = params[:date]
      @events = @date == 'upcoming' ? Event.upcoming : Event.past
    else
      @events = Event.latest
    end
  end

  # POST /events/attend/1
  def attend
    attend = Attend.new(event_id: @event.id, user_id: current_user.id)
    if attend.save
      redirect_to @event, notice: 'Te has inscrito al evento'
    else
      redirect_to @event, alert: 'Hubo un problema al inscribirte al evento'
    end
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @comment = Comment.new
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:name, :details, :starts_at, :ends_at, :location, :image)
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.haml
.page-header.header-filter{"data-parallax" => "true", "filter-color" => "white", :style => "background-image: url('#{asset_path('bg.jpg')}');"}
  .container
    .row.title-row
.section.section-gray
  .container
    .main.main-raised.main-product.py-0
      .row
        .col-12
          = form_for @event do |f|
            %h3.title= title
            - if @event.errors.any?
              #error_explanation
                %h2= "#{pluralize(@event.errors.count, "error")} prohibited this event from being saved:"
                %ul
                  - @event.errors.full_messages.each do |message|
                    %li= message

            .form-group.bmd-form-group
              = f.label :name, class: 'bmd-label-floating'
              = f.text_field :name, class: 'form-control'
            .form-group.bmd-form-group
              = f.label :details, class: 'bmd-label-floating'
              = f.text_area :details, class: 'form-control', size: "12x5"
            .form-group.form-file-upload.form-file-multiple
              = f.file_field :image, class: 'inputFileHidden'
              .input-group
                %input.form-control.inputFileVisible{:multiple => "multiple", :placeholder => "Selecciona la imágen del evento", :type => "text"}
                %span.input-group-btn
                  %button.btn.btn-fab.btn-round.btn-info{:type => "button"}
                    %i.material-icons attach_file
            .form-group.bmd-form-group
              = f.label :starts_at
              = f.text_field :starts_at, class: 'form-control datetimepicker'
            .form-group.bmd-form-group
              = f.label :ends_at
              = f.text_field :ends_at, class: 'form-control datetimepicker'
            .form-group.bmd-form-group
              = f.label :location, class: 'bmd-label-floating'
              = f.text_field :location, class: 'form-control'
            .text-center
              = f.submit 'Guardar evento', class: 'btn btn-success btn-wd'
:javascript
  $('.datetimepicker').datetimepicker({
    icons: {
      time: "fa fa-clock-o",
      date: "fa fa-calendar",
      up: "fa fa-chevron-up",
      down: "fa fa-chevron-down",
      previous: 'fa fa-chevron-left',
      next: 'fa fa-chevron-right',
      today: 'fa fa-screenshot',
      clear: 'fa fa-trash',
      close: 'fa fa-remove'
    }
  });

app/views/events/edit.html.haml
= render 'form', title: 'Editar evento'

app/views/events/index.html.haml
= page_header("Todos los eventos", "Enterate y asiste a los eventos cercanos.", "#{asset_path("bg.jpg")}")

.main.main-raised
  .section.py-2
    .container
      .row
        .col-12.text-center
          %ul.nav.nav-pills.nav-pills-rose.row.justify-content-center
            %li.nav-item
              = link_to 'Todos', events_path, class: "nav-link #{ 'active' if !@date}"
            %li.nav-item
              = link_to 'Pasados', events_path(date: 'past'), class: "nav-link #{ 'active' if @date == 'past'}"
            %li.nav-item
              = link_to 'Próximos', events_path(date: 'upcoming'), class: "nav-link #{ 'active' if @date == 'upcoming'}"
        .col-md-12
          .row
            - @events.each do |event|
              .col-md-4
                .card.card-blog
                  .card-header.card-header-image
                    = link_to event do
                      - if event.image.attached?
                        = image_tag url_for(event.image), :fetch_format=>:auto, :crop=>"scale", class: "img"
                      - else
                        %img.img{:src => "https://demos.creative-tim.com/material-kit-pro/assets/img/examples/office1.jpg"}/
                      .card-title
                        = event.name
                  .card-body.pb-1.pl-3
                    %span.badge.badge-rose #mtb
                    %span.badge.badge-rose #ride
                    %p.card-description= truncate(event.details, length: 90)
                  .card-footer.d-block.pl-3
                    .stats
                      %span
                        %i.material-icons access_time
                        = event.starts_at.strftime("%b %d")
                        ─
                        = event.ends_at.strftime("%b %d")
                    .mt-1
                      = link_to "Ver más", event, class: "btn btn-round btn-sm btn-primary"
                  -# - if event.image.attached?
                  -#   .card-header.card-header-image
                  -#     = link_to event do
                  -#       = image_tag url_for(event.image), :fetch_format=>:auto, :crop=>"scale"
                  -#       = distance_of_time_in_words_to_now(event.starts_at)

app/views/events/new.html.haml
= render 'form', title: 'Nuevo evento'

app/views/events/show.html.haml
.page-header.header-filter{"data-parallax" => "true", "filter-color" => "bluex  ", :style => "background-image: url('#{asset_path('bg.jpg')}');"}
  -# .container
    -# .row
.section.section-gray
  .container
    .row
      .main.main-raised.main-product.col-sm-12.col-md-10.col-lg-8.ml-auto.mr-auto.col-sm-12
        - if @event.image.attached?
          = image_tag url_for(@event.image), :fetch_format=>:auto, :crop=>"scale", class: 'img-fluid rounded img-raised'
        - else
          %img.img-fluid.img-raised.rounded{:src => "https://demos.creative-tim.com/material-kit-pro/assets/img/examples/office1.jpg"}/
      
        %h2.title.mt-0= @event.name
        %h3.main-price.mb-0
          %span
            %i.material-icons access_time
            = @event.starts_at.strftime("%b %d")
            ─
            = @event.ends_at.strftime("%b %d")
        %span.badge.badge-pill.badge-info
          = pluralize(@event.users.count, 'persona')
          asistirán al evento.
        %p.mt-2= @event.details
        .row.justify-content-end
          - if user_signed_in?
            - if !@event.users.include?(current_user)
              = button_to attend_path(id: @event.id), method: :post, class: " btn btn-success btn-round" do
                ️☝️ Inscribirme
            - else
              = link_to '#0', class: " btn btn-success btn-round disabled" do
                🎉 Ya estás inscrito 🎉
            = link_to @event, class: " btn btn-info btn-round ml-2" do
              ️🔗 Ir a la página
        .mt-4
        - if user_signed_in?
        
          -# .col-12.d-flex.justify-content-between
          -#   %h3.title Opininiones
          -#   %span
          -#     %i.material-icons person
          -#     = @event.comments.count
          -#     en total
          .col-12
            .media-area
              %h3.title.text-center
                = pluralize(@event.comments.count, "comentario")
              = render @event.comments
            %h4.title.my-0 Deja tu opinión del evento
            = render 'comments/form'
        
        -# .card.card-collapse
        -#   #headingThree.card-header{:role => "tab"}
        -#     %h5.mb-0
        -#       %a.collapsed{"aria-controls" => "collapseThree", "aria-expanded" => "false", "data-toggle" => "collapse", :href => "#collapseThree"}
        -#         Details and Care
        -#         %i.material-icons keyboard_arrow_down
        -#   #collapseThree.collapse{"aria-labelledby" => "headingThree", "data-parent" => "#accordion", :role => "tabpanel"}
        -#     .card-body
        -#       %ul
        -#         %li Storm and midnight-blue stretch cotton-blend
        -#         %li
        -#           Notch lapels, functioning buttoned cuffs, two front flap pockets,
        -#           single vent, internal pocket
        -#         %li Two button fastening
        -#         %li 84% cotton, 14% nylon, 2% elastane
        -#         %li Dry clean
      -# .row.pull-right
      -#   = render 'in_shopping_carts/form', product: @product
  -# .features.text-center
  -#   .row
  -#     .col-md-4
  -#       .info
  -#         .icon.icon-info
  -#           %i.material-icons local_shipping
  -#         %h4.info-title 2 días de entrega
  -#         %p
  -#           Te garantizamos el menor tiempo posible de entrega para tu producto.
  -#     .col-md-4
  -#       .info
  -#         .icon.icon-success
  -#           %i.material-icons verified_user
  -#         %h4.info-title Política reembolsable
  -#         %p
  -#           Si no estás conforme con tu producto te devolverémos tu dinero.
  -#     .col-md-4
  -#       .info
  -#         .icon.icon-rose
  -#           %i.material-icons favorite
  -#         %h4.info-title Alta confiabilidad
  -#         %p
  -#           Nuestros proveedores son 100% confiables y de la mejor calidad.
  -# .related-products
  -#   %h3.title.text-center También puedes estar interesado en:
  -#   .row
  -#     - @random.each do |product|
  -#       .col-lg-3.col-md-6
  -#         .card.card-product
  -#           - if product.images.any?
  -#             .card-header.card-header-image
  -#               = link_to product do
  -#                 = image_tag url_for(product.images.first), :fetch_format=>:auto, :crop=>"scale"
  -#           .card-body
  -#             %h6.card-category.text-rose= product.category.name
  -#             = link_to product do
  -#               %h4.card-title= truncate(product.name, length: 40, separator: '...')
  -#             .card-description
  -#               %p= truncate(product.description, length: 50, separator: '...')
  -#               .price.price-new
  -#                 %h4
  -#                   $
  -#                   = product.pricing