config/routes.rb
Rails.application.routes.draw do
  resources :bicycle_shops, only: [:index]
  devise_for :users, controllers: {
    'omniauth_callbacks': 'users/omniauth_callbacks'
  }
  
  resources :events, only: [:index, :show] do
    resources :comments, only: [:create,:destroy]
  end
  resources :categories, only: [:index, :show]
  resources :products, only: [:index, :show]
  resources :in_shopping_carts, only: [:create, :destroy, :update]

  root 'products#index'

  # Admin routes
  namespace :admin do
    resources :users
    resources :categories
    resources :events
    resources :my_payments
    resources :products

    root "products#index"
  end
  

  get '/cart', to: 'shopping_carts#show'
  get '/add/:product_id', as: :add_to_cart, to: 'in_shopping_carts#create'
  get '/checkout', to: 'payments#checkout'
  get '/ok', to: 'home#success'
  # get '/download/:id', to: 'links#download'
  # get '/download/:id/file/:attachment_id', to: 'links#download_attachment', as: :download_attachment
  # get '/invalid', to: 'welcome#unregistered'
  get '/orders', to: 'orders#index'
  get '/about', to: 'home#about'
  get '/terms', to: 'home#terms'

  post '/pay', to: 'payments#create'
  post 'payments/cards', to: 'payments#process_card'

  post '/events/:id/attend', to: 'events#attend', as: :attend

  post '/custom_sign_up', to: 'users/omniauth_callbacks#custom_sign_up'
end

app/models/category.rb
# == Schema Information
#
# Table name: categories
#
#  id         :bigint(8)        not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Category < ApplicationRecord
  validates :name, presence: true
  has_many :products
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @categories = Category.all
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.haml
.page-header.header-filter{"data-parallax" => "true", "filter-color" => "white", :style => "background-image: url('#{asset_path('bg.jpg')}');"}
  .container
    .row.title-row
.section.section-gray
  .container
    .main.main-raised.main-product.py-0
      .row
        .col-12
          = form_for @category, html: {class: 'form'} do |f|
            %h3.title= title
            - if @category.errors.any?
              #error_explanation
                %h2= "#{pluralize(@product.errors.count, "error")} al guardar este producto:"
                %ul
                  - @product.errors.full_messages.each do |message|
                    %li= message
            .form-group.bmd-form-group
              = f.label :name, 'Nombre de la categoría', class: 'bmd-label-floating'
              = f.text_field :name, required: true, class: 'form-control'
            .text-center
              = f.submit 'Guardar categoría', class: 'btn btn-success btn-wd'

app/views/categories/edit.html.haml
= render 'form', title: 'Editar categoría'

app/views/categories/index.html.haml
.page-header.header-filter{"data-parallax" => "true", "filter-color" => "white", :style => "background-image: url('#{asset_path('bg.jpg')}');"}
  .container
    .row.title-row
.section.section-gray
  .container
    .main.main-raised.main-product.py-0
      .row
        .col-md-12.ml-auto.mr-auto
          %h2.title.text-center Categorías disponibles
        - @categories.each do |category|
          .col-lg-3.col-sm-6.col-12
            .card.card-raised.card-background{style: "background: url(#{asset_path 'bg.jpg'}) center / cover"}
              .card-body{style: 'min-height: auto'}
                = link_to category do
                  %h3.card-title= category.name
                = link_to category, class: 'btn btn-danger btn-round' do
                  %i.material-icons touch_app
                  Ver

app/views/categories/new.html.haml
= render 'form', title: 'Nuevo categoría'

app/views/categories/show.html.haml
.page-header.header-filter{"data-parallax" => "true", "filter-color" => "white", :style => "background-image: url('#{asset_path('bg.jpg')}');"}
  .container
    .row.title-row
.section.section-gray
  .container
    .main.main-raised.main-product
      .row
        .col-12.text-center
          %h3.title
            Productos en:
            = @category.name
          %ul.nav.nav-pills.nav-pills-rose.row.justify-content-center
            %li.nav-item
              = link_to 'Todas las categorías', categories_path, class: 'nav-link'
            - @categories.each do |category|
              %li.nav-item
                = link_to category.name, category, class: "nav-link #{ 'active' if category.id == @category.id}"
        - @category.products.each do |product|
          .col-lg-3.col-md-6
            .card.card-product
              - if product.images.any?
                .card-header.card-header-image
                  = link_to product do
                    = image_tag url_for(product.images.first), :fetch_format=>:auto, :crop=>"scale"
              .card-body
                %h6.card-category.text-rose= link_to product.category.name, product.category
                = link_to product do
                  %h4.card-title= truncate(product.name, length: 40, separator: '...')
                .card-description
                  %p= truncate(product.description, length: 50, separator: '...')
                  .price.price-new
                    %h4
                      $
                      = product.pricing